Must be misreading the documentation

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,9 +51,9 @@ test-e2e:
       RESPONSE=$(curl --netrc-file login-curl.txt http://localhost:8198/request)
       for STR in "${EXPECTED[@]}"; do
       echo "$RESPONSE" | grep -q "$STR" || { \
-        echo "Response missing expected string: $STR" >&2 \
-        docker compose down \
-        exit 1 \
+      echo "Response missing expected string: $STR" >&2 \
+      docker compose down \
+      exit 1 \
       }
       done
     - docker compose down
