Not becoming desperate at all

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,10 +46,18 @@ test-e2e:
   script:
     - docker compose up -d
     - sleep 5
-    - >
-      EXPECTED=("Service1:" "Service2:" "Filesystem" "PID" "TTY" "STAT" "COMMAND")
-      RESPONSE=$(curl --netrc-file login-curl.txt http://localhost:8198/request)
-      for STR in "${EXPECTED[@]}"; do if [[ ! "$RESPONSE" =~ "$STR" ]]; then echo "Response missing expected string: $STR"; fi; done
+    - bash -c '
+        EXPECTED=("Service1:" "Service2:" "Filesystem" "PID" "TTY" "STAT" "COMMAND")
+        RESPONSE=$(curl --netrc-file login-curl.txt http://localhost:8198/request)
+        for STR in "${EXPECTED[@]}"; do
+          if [[ ! "$RESPONSE" =~ "$STR" ]]; then
+            echo "Response missing expected string: $STR"
+            docker compose down
+            exit 1
+          fi
+        done
+        echo "Test successful"
+      '
     - docker compose down
 
 deploy-job:
